from .index_view import MAIndexView
from .object_view import MAObjectCreateView, MAObjectUpdateView, MAObjectDeleteView
from .object_column_view import MAObjectColumnListView, MAObjectColumnCreateView, MAObjectColumnUpdateView, MAObjectColumnDeleteView
from .reg_object_view import MARegObjectView
from .reg_object_view import MAToApproveObjectView
