# Generated by Django 5.2.12 on 2026-04-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicTableSchema",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "object_name",
                    models.CharField(max_length=255, verbose_name="Имя объекта  БД"),
                ),
                (
                    "schema_json",
                    models.JSONField(
                        help_text="JSON с описанием полей", verbose_name="Схема таблицы"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Динамическая таблица",
                "verbose_name_plural": "Динамические таблицы",
                "db_table": '"meta_app"."dynamic_table_schema"',
                "ordering": ["-created_at"],
            },
        ),
    ]
