# Generated by Django 5.2.12 on 2026-04-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_tables_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamictableschema",
            name="schema_name",
            field=models.CharField(
                default="public", max_length=255, verbose_name="Схема объекта БД"
            ),
        ),
    ]
