# Generated by Django 5.2.12 on 2026-04-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamic_tables_app", "0002_dynamictableschema_schema_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dynamictableschema",
            name="object_name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Имя объекта  БД"
            ),
        ),
    ]
