# Generated by Django 5.2.12 on 2026-04-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="staff_code",
            field=models.CharField(max_length=255, verbose_name="Табельный номер"),
        ),
    ]
