# Generated by Django 5.2.12 on 2026-04-04 22:32

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dicuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата и время создания объекта",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dicuser",
            name="created_by",
            field=models.CharField(
                default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AddField(
            model_name="dicuser",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Дата и время обновления объекта"
            ),
        ),
        migrations.AddField(
            model_name="dicuser",
            name="updated_by",
            field=models.CharField(
                null=True, verbose_name="Пользователь обновивший запись"
            ),
        ),
        migrations.AddField(
            model_name="dicuser",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Уникальный идентификатор записи",
            ),
        ),
        migrations.AlterField(
            model_name="dicdepartment",
            name="created_by",
            field=models.CharField(
                default="", verbose_name="Пользователь создавший запись"
            ),
        ),
    ]
