# Generated by Django 5.2.12 on 2026-04-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0003_remove_user_user_name_alter_user_staff_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_by",
            field=models.CharField(
                blank=True, default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_by",
            field=models.CharField(
                blank=True, null=True, verbose_name="Пользователь обновивший запись"
            ),
        ),
    ]
