# Generated by Django 5.2.12 on 2026-04-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0004_alter_user_created_by_alter_user_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_by",
            field=models.CharField(
                default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_by",
            field=models.CharField(
                null=True, verbose_name="Пользователь обновивший запись"
            ),
        ),
    ]
