# Generated by Django 5.2.12 on 2026-04-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0005_alter_user_created_by_alter_user_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_by",
            field=models.CharField(
                blank=True, default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_by",
            field=models.CharField(
                blank=True, null=True, verbose_name="Пользователь обновивший запись"
            ),
        ),
    ]
