# Generated by Django 5.2.12 on 2026-04-26 15:05

import django.db.models.deletion
import mptt.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttrGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "group_code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Код группы"
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование группы"
                    ),
                ),
                (
                    "group_description",
                    models.TextField(
                        null=True, verbose_name="Детальное описание группы"
                    ),
                ),
                (
                    "group_params",
                    models.JSONField(null=True, verbose_name="Параметры группы"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь создавший запись",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь обновивший запись",
                    ),
                ),
            ],
            options={
                "db_table": '"meta_app"."attr_group"',
            },
        ),
        migrations.CreateModel(
            name="AttrType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Код типа"
                    ),
                ),
                (
                    "type_name",
                    models.CharField(max_length=255, verbose_name="Наименование типа"),
                ),
                (
                    "type_description",
                    models.TextField(null=True, verbose_name="Детальное описание типа"),
                ),
                (
                    "tech_type_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Техническое название"
                    ),
                ),
                (
                    "type_params",
                    models.JSONField(null=True, verbose_name="Параметры типа"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь создавший запись",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь обновивший запись",
                    ),
                ),
            ],
            options={
                "db_table": '"meta_app"."attr_type"',
            },
        ),
        migrations.CreateModel(
            name="Attr",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "attr_code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Код атрибута"
                    ),
                ),
                (
                    "attr_name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование атрибута"
                    ),
                ),
                (
                    "attr_description",
                    models.TextField(
                        null=True, verbose_name="Детальное описание атрибута"
                    ),
                ),
                (
                    "attr_params",
                    models.JSONField(null=True, verbose_name="Параметры атрибута"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь создавший запись",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь обновивший запись",
                    ),
                ),
                (
                    "attr_group",
                    models.ForeignKey(
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="+",
                        to="meta_app.attrgroup",
                        verbose_name="Группа атрибута",
                    ),
                ),
                (
                    "attr_type",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="meta_app.attrtype",
                        verbose_name="Тип атрибута",
                    ),
                ),
            ],
            options={
                "db_table": '"meta_app"."attr"',
            },
        ),
        migrations.CreateModel(
            name="Object",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "dic_code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Код объекта"
                    ),
                ),
                (
                    "dic_name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование объекта"
                    ),
                ),
                (
                    "dic_description",
                    models.TextField(verbose_name="Детальное описание объекта"),
                ),
                (
                    "schema_name",
                    models.CharField(max_length=255, verbose_name="Схема объекта БД"),
                ),
                (
                    "object_name",
                    models.CharField(max_length=255, verbose_name="Имя объекта  БД"),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[("VIEW", "Представление"), ("TABLE", "Таблица")],
                        default="TABLE",
                        max_length=255,
                        verbose_name="Тип объекта  БД",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь создавший запись",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь обновивший запись",
                    ),
                ),
            ],
            options={
                "db_table": '"meta_app"."object"',
            },
        ),
        migrations.CreateModel(
            name="ObjectAttrValue",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                ("value", models.TextField(verbose_name="Значение атрибута")),
                (
                    "value_params",
                    models.JSONField(
                        null=True, verbose_name="Параметры значения атрибута"
                    ),
                ),
                (
                    "attr_type",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="meta_app.attrtype",
                        verbose_name="Тип атрибута",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="meta_app.attr",
                        verbose_name="Идентификатор атрибута справочника",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь создавший запись",
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="meta_app.object",
                        verbose_name="Идентификатор справочника",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь обновивший запись",
                    ),
                ),
            ],
            options={
                "db_table": '"meta_app"."object_attr_value"',
            },
        ),
        migrations.CreateModel(
            name="ObjectAttrValueRelation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "value",
                    models.TextField(null=True, verbose_name="Значение атрибута"),
                ),
                (
                    "value_params",
                    models.JSONField(
                        null=True, verbose_name="Параметры значения атрибута"
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="meta_app.attr",
                        verbose_name="Идентификатор атрибута справочника",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь создавший запись",
                    ),
                ),
                (
                    "object_attr_value",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="meta_app.objectattrvalue",
                        verbose_name="ИД на значение атрибута объекта",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь обновивший запись",
                    ),
                ),
            ],
            options={
                "db_table": '"meta_app"."object_attr_value_ralation"',
            },
        ),
        migrations.CreateModel(
            name="ObjectColumn",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "column_name",
                    models.CharField(max_length=255, verbose_name="Название колонки"),
                ),
                (
                    "column_description",
                    models.TextField(
                        null=True, verbose_name="Детальное описание колонки"
                    ),
                ),
                (
                    "is_null",
                    models.BooleanField(default=True, verbose_name="Обязательность"),
                ),
                (
                    "ordinal_position",
                    models.FloatField(default=0.0, verbose_name="Порядок следования"),
                ),
                (
                    "is_pk",
                    models.BooleanField(default=False, verbose_name="Первичный ключ"),
                ),
                (
                    "column_type",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="meta_app.attrtype",
                        verbose_name="Тип колонки",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь создавший запись",
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="meta_app.object",
                        verbose_name="Идентификатор справочника",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь обновивший запись",
                    ),
                ),
            ],
            options={
                "db_table": '"meta_app"."object_column"',
            },
        ),
        migrations.CreateModel(
            name="ObjectRegistration",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "is_approve",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Согласование"
                    ),
                ),
                (
                    "approve_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время согласования"
                    ),
                ),
                (
                    "approve_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь согласовавший справочник",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь создавший запись",
                    ),
                ),
                (
                    "dictionary",
                    models.OneToOneField(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="meta_app.object",
                        verbose_name="Идентификатор справочника",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь обновивший запись",
                    ),
                ),
            ],
            options={
                "db_table": '"meta_app"."object_registration"',
            },
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "structure_code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Код структуры"
                    ),
                ),
                (
                    "structure_name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование структуры"
                    ),
                ),
                (
                    "structure_description",
                    models.TextField(verbose_name="Детальное описание структуры"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь создавший запись",
                    ),
                ),
                (
                    "structure_parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="meta_app.structure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь обновивший запись",
                    ),
                ),
            ],
            options={
                "db_table": '"meta_app"."structure"',
            },
        ),
        migrations.CreateModel(
            name="ObjectStructureLink",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь создавший запись",
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dictonary",
                        to="meta_app.object",
                        verbose_name="Идентификатор справочника",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь обновивший запись",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure",
                        to="meta_app.structure",
                        verbose_name="Идентификатор структуры",
                    ),
                ),
            ],
            options={
                "db_table": '"meta_app"."object_structure_link"',
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dictionary_id", "structure_id"),
                        name="UQ_dictionary_structure",
                    )
                ],
            },
        ),
    ]
