# Generated by Django 6.0.3 on 2026-03-24 20:34

import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("meta_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DicAttrGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(verbose_name="Пользователь создавший запись"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        null=True, verbose_name="Пользователь обновивший запись"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "group_code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Код группы"
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование группы"
                    ),
                ),
                (
                    "group_description",
                    models.TextField(
                        null=True, verbose_name="Детальное описание группы"
                    ),
                ),
            ],
            options={
                "db_table": 'meta"."dic_attr_group',
            },
        ),
        migrations.CreateModel(
            name="DicAttrType",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(verbose_name="Пользователь создавший запись"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        null=True, verbose_name="Пользователь обновивший запись"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "type_code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Код типа"
                    ),
                ),
                (
                    "type_name",
                    models.CharField(max_length=255, verbose_name="Наименование типа"),
                ),
                (
                    "type_description",
                    models.TextField(null=True, verbose_name="Детальное описание типа"),
                ),
            ],
            options={
                "db_table": 'meta"."dic_attr_type',
            },
        ),
        migrations.CreateModel(
            name="DicObject",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(verbose_name="Пользователь создавший запись"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        null=True, verbose_name="Пользователь обновивший запись"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "dic_code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Код объекта"
                    ),
                ),
                (
                    "dic_name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование объекта"
                    ),
                ),
                (
                    "dic_description",
                    models.TextField(verbose_name="Детальное описание объекта"),
                ),
                (
                    "schema_name",
                    models.CharField(max_length=255, verbose_name="Схема объекта БД"),
                ),
                (
                    "object_name",
                    models.CharField(max_length=255, verbose_name="Имя объекта  БД"),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[("VIEW", "Представление"), ("TABLE", "Таблица")],
                        default="TABLE",
                        max_length=255,
                        verbose_name="Тип объекта  БД",
                    ),
                ),
            ],
            options={
                "db_table": 'meta"."dic_object',
            },
        ),
        migrations.CreateModel(
            name="DicObjectAttrValueStr",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(verbose_name="Пользователь создавший запись"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        null=True, verbose_name="Пользователь обновивший запись"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                ("value", models.TextField(verbose_name="Значение атрибута")),
            ],
            options={
                "db_table": 'meta"."dic_object_attr_value_str',
            },
        ),
        migrations.CreateModel(
            name="DicObjectAttr",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(verbose_name="Пользователь создавший запись"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        null=True, verbose_name="Пользователь обновивший запись"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "attr_name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование атрибута"
                    ),
                ),
                (
                    "attr_code",
                    models.CharField(
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Код атрибута",
                    ),
                ),
                (
                    "attr_description",
                    models.TextField(
                        null=True, verbose_name="Детальное описание атрибута"
                    ),
                ),
                (
                    "attr_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="+",
                        to="meta_app.dicattrgroup",
                        verbose_name="Группа атрибута",
                    ),
                ),
                (
                    "attr_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="meta_app.dicattrtype",
                        verbose_name="Тип атрибута",
                    ),
                ),
            ],
            options={
                "db_table": 'meta"."dic_object_attr',
            },
        ),
        migrations.CreateModel(
            name="DicObjectAttrValueDecimal",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(verbose_name="Пользователь создавший запись"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        null=True, verbose_name="Пользователь обновивший запись"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=9,
                        verbose_name="Значение атрибута",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="meta_app.dicobjectattr",
                        verbose_name="Идентификатор атрибута справочника",
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_attributes",
                        to="meta_app.dicobject",
                        verbose_name="Идентификатор справочника",
                    ),
                ),
            ],
            options={
                "db_table": 'meta"."dic_object_attr_value_decimal',
            },
        ),
        migrations.CreateModel(
            name="DicObjectAttrValueInt",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(verbose_name="Пользователь создавший запись"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        null=True, verbose_name="Пользователь обновивший запись"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                ("value", models.IntegerField(verbose_name="Значение атрибута")),
                (
                    "attribute",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="meta_app.dicobjectattr",
                        verbose_name="Идентификатор атрибута справочника",
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_attributes",
                        to="meta_app.dicobject",
                        verbose_name="Идентификатор справочника",
                    ),
                ),
            ],
            options={
                "db_table": 'meta"."dic_object_attr_value_int',
            },
        ),
        migrations.CreateModel(
            name="DicObjectAttrValueJson",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(verbose_name="Пользователь создавший запись"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        null=True, verbose_name="Пользователь обновивший запись"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                ("value", models.JSONField(verbose_name="Значение атрибута")),
                (
                    "attribute",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="meta_app.dicobjectattr",
                        verbose_name="Идентификатор атрибута справочника",
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_attributes",
                        to="meta_app.dicobject",
                        verbose_name="Идентификатор справочника",
                    ),
                ),
            ],
            options={
                "db_table": 'meta"."dic_object_attr_value_json',
            },
        ),
        migrations.CreateModel(
            name="DicObjectColumn",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(verbose_name="Пользователь создавший запись"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        null=True, verbose_name="Пользователь обновивший запись"
                    ),
                ),
                (
                    "column",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="attr",
                        serialize=False,
                        to="meta_app.dicobjectattrvaluestr",
                        verbose_name="Идентификатор колонки",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "column_name",
                    models.CharField(max_length=255, verbose_name="Название колонки"),
                ),
                (
                    "column_description",
                    models.TextField(
                        null=True, verbose_name="Детальное описание колонки"
                    ),
                ),
                (
                    "is_null",
                    models.BooleanField(default=True, verbose_name="Обязательность"),
                ),
                (
                    "ordinal_position",
                    models.FloatField(default=0.0, verbose_name="Порядок следования"),
                ),
                (
                    "is_pk",
                    models.BooleanField(default=False, verbose_name="Первичный ключ"),
                ),
                (
                    "column_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="meta_app.dicattrtype",
                        verbose_name="Тип колонки",
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column",
                        to="meta_app.dicobject",
                        verbose_name="Идентификатор справочника",
                    ),
                ),
            ],
            options={
                "db_table": 'meta"."dic_object_column',
            },
        ),
        migrations.AddField(
            model_name="dicobjectattrvaluestr",
            name="attribute",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                related_query_name="+",
                to="meta_app.dicobjectattr",
                verbose_name="Идентификатор атрибута справочника",
            ),
        ),
        migrations.AddField(
            model_name="dicobjectattrvaluestr",
            name="dictionary",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_attributes",
                to="meta_app.dicobject",
                verbose_name="Идентификатор справочника",
            ),
        ),
        migrations.CreateModel(
            name="DicObjectRegister",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(verbose_name="Пользователь создавший запись"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        null=True, verbose_name="Пользователь обновивший запись"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "dictionary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="register",
                        to="meta_app.dicobject",
                        verbose_name="Идентификатор справочника",
                    ),
                ),
            ],
            options={
                "db_table": 'meta"."dic_object_register',
            },
        ),
        migrations.CreateModel(
            name="DicStructure",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(verbose_name="Пользователь создавший запись"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        null=True, verbose_name="Пользователь обновивший запись"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "structure_code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Код структуры"
                    ),
                ),
                (
                    "structure_name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование структуры"
                    ),
                ),
                (
                    "structure_description",
                    models.TextField(verbose_name="Детальное описание структуры"),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "structure_parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="meta_app.dicstructure",
                    ),
                ),
            ],
            options={
                "db_table": 'meta"."dic_structure',
            },
        ),
        migrations.CreateModel(
            name="DicRelationship",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(verbose_name="Пользователь создавший запись"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        null=True, verbose_name="Пользователь обновивший запись"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "foreign_column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="meta_app.dicobjectcolumn",
                        verbose_name="ИД колонки",
                    ),
                ),
                (
                    "references_column",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="meta_app.dicobjectcolumn",
                        verbose_name="ИД ссылочной колонки",
                    ),
                ),
            ],
            options={
                "db_table": 'meta"."dic_relationship',
            },
        ),
        migrations.CreateModel(
            name="DicObjectStructureLink",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(verbose_name="Пользователь создавший запись"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        null=True, verbose_name="Пользователь обновивший запись"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                (
                    "dictionary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dictonary",
                        to="meta_app.dicobject",
                        verbose_name="Идентификатор справочника",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure",
                        to="meta_app.dicstructure",
                        verbose_name="Идентификатор структуры",
                    ),
                ),
            ],
            options={
                "db_table": 'meta"."dic_object_structure_link',
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dictionary_id", "structure_id"),
                        name="UQ_dictionary_structure",
                    )
                ],
            },
        ),
    ]
