# Generated by Django 5.2.12 on 2026-04-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="object",
            name="object_name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Имя объекта  БД"
            ),
        ),
    ]
