# Generated by Django 5.2.12 on 2026-04-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dicattr",
            name="created_by",
            field=models.CharField(
                default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="dicattrgroup",
            name="created_by",
            field=models.CharField(
                default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="dicattrtype",
            name="created_by",
            field=models.CharField(
                default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="dicobject",
            name="created_by",
            field=models.CharField(
                default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="dicobjectattrvalue",
            name="created_by",
            field=models.CharField(
                default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="dicobjectattrvaluerelation",
            name="created_by",
            field=models.CharField(
                default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="dicobjectcolumn",
            name="created_by",
            field=models.CharField(
                default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="dicobjectstructurelink",
            name="created_by",
            field=models.CharField(
                default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="dicstructure",
            name="created_by",
            field=models.CharField(
                default="", verbose_name="Пользователь создавший запись"
            ),
        ),
    ]
