# Generated by Django 5.2.12 on 2026-04-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dicattrgroup",
            name="group_params",
            field=models.JSONField(null=True, verbose_name="Параметры группы"),
        ),
        migrations.AddField(
            model_name="dicattrtype",
            name="type_params",
            field=models.JSONField(null=True, verbose_name="Параметры типа"),
        ),
        migrations.AlterField(
            model_name="dicobjectattrvaluerelation",
            name="value",
            field=models.TextField(null=True, verbose_name="Значение атрибута"),
        ),
    ]
