# Generated by Django 5.2.12 on 2026-04-22 22:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_app", "0003_alter_objectcolumn_dictionary_objectregistratration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="ObjectRegistratration",
        ),
        migrations.CreateModel(
            name="ObjectRegistration",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания объекта"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name="Дата и время обновления объекта",
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор записи",
                    ),
                ),
                ("is_approve", models.BooleanField(verbose_name="Согласование")),
                (
                    "approve_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время согласования"
                    ),
                ),
                (
                    "approve_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь согласовавший справочник",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь создавший запись",
                    ),
                ),
                (
                    "dictionary",
                    models.OneToOneField(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="meta_app.object",
                        verbose_name="Идентификатор справочника",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь обновивший запись",
                    ),
                ),
            ],
            options={
                "db_table": '"meta_app"."object_registration"',
            },
        ),
    ]
