# Generated by Django 5.2.12 on 2026-04-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_app", "0004_alter_attr_created_by_alter_attr_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attr",
            name="created_by",
            field=models.CharField(
                blank=True, default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="attr",
            name="updated_by",
            field=models.CharField(
                blank=True, null=True, verbose_name="Пользователь обновивший запись"
            ),
        ),
        migrations.AlterField(
            model_name="attrgroup",
            name="created_by",
            field=models.CharField(
                blank=True, default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="attrgroup",
            name="updated_by",
            field=models.CharField(
                blank=True, null=True, verbose_name="Пользователь обновивший запись"
            ),
        ),
        migrations.AlterField(
            model_name="attrtype",
            name="created_by",
            field=models.CharField(
                blank=True, default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="attrtype",
            name="updated_by",
            field=models.CharField(
                blank=True, null=True, verbose_name="Пользователь обновивший запись"
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="created_by",
            field=models.CharField(
                blank=True, default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="object",
            name="updated_by",
            field=models.CharField(
                blank=True, null=True, verbose_name="Пользователь обновивший запись"
            ),
        ),
        migrations.AlterField(
            model_name="objectattrvalue",
            name="created_by",
            field=models.CharField(
                blank=True, default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="objectattrvalue",
            name="updated_by",
            field=models.CharField(
                blank=True, null=True, verbose_name="Пользователь обновивший запись"
            ),
        ),
        migrations.AlterField(
            model_name="objectattrvaluerelation",
            name="created_by",
            field=models.CharField(
                blank=True, default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="objectattrvaluerelation",
            name="updated_by",
            field=models.CharField(
                blank=True, null=True, verbose_name="Пользователь обновивший запись"
            ),
        ),
        migrations.AlterField(
            model_name="objectcolumn",
            name="created_by",
            field=models.CharField(
                blank=True, default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="objectcolumn",
            name="updated_by",
            field=models.CharField(
                blank=True, null=True, verbose_name="Пользователь обновивший запись"
            ),
        ),
        migrations.AlterField(
            model_name="objectstructurelink",
            name="created_by",
            field=models.CharField(
                blank=True, default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="objectstructurelink",
            name="updated_by",
            field=models.CharField(
                blank=True, null=True, verbose_name="Пользователь обновивший запись"
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="created_by",
            field=models.CharField(
                blank=True, default="", verbose_name="Пользователь создавший запись"
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="updated_by",
            field=models.CharField(
                blank=True, null=True, verbose_name="Пользователь обновивший запись"
            ),
        ),
    ]
