# Generated by Django 5.2.12 on 2026-04-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_app", "0004_objectregistration_delete_objectregistratration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectregistration",
            name="is_approve",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Согласование"
            ),
        ),
    ]
