# Generated by Django 5.2.12 on 2026-04-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_app", "0005_alter_objectregistration_is_approve"),
    ]

    operations = [
        migrations.AddField(
            model_name="attrtype",
            name="tech_type_name",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Техническое название"
            ),
        ),
    ]
